/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Codigo;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author aghsk
 */
public class PanelColores extends javax.swing.JPanel {

    public Color colorSeleccionado = Color.BLACK;

    /**
     * Creates new form PanelColores
     */
    public PanelColores() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Color1 = new javax.swing.JLabel();
        Color2 = new javax.swing.JLabel();
        Color3 = new javax.swing.JLabel();
        Color4 = new javax.swing.JLabel();
        Color5 = new javax.swing.JLabel();
        Color6 = new javax.swing.JLabel();
        Color7 = new javax.swing.JLabel();
        Color8 = new javax.swing.JLabel();
        Color9 = new javax.swing.JLabel();
        Color10 = new javax.swing.JLabel();
        Color11 = new javax.swing.JLabel();
        Color12 = new javax.swing.JLabel();
        Color13 = new javax.swing.JLabel();
        Color14 = new javax.swing.JLabel();
        Color15 = new javax.swing.JLabel();
        Color16 = new javax.swing.JLabel();
        Color17 = new javax.swing.JLabel();
        Color18 = new javax.swing.JLabel();
        Color19 = new javax.swing.JLabel();
        Color20 = new javax.swing.JLabel();
        Color21 = new javax.swing.JLabel();
        Color22 = new javax.swing.JLabel();
        Color23 = new javax.swing.JLabel();
        Color24 = new javax.swing.JLabel();
        Color25 = new javax.swing.JLabel();
        Color26 = new javax.swing.JLabel();
        Color27 = new javax.swing.JLabel();
        Color28 = new javax.swing.JLabel();
        Color29 = new javax.swing.JLabel();
        Color30 = new javax.swing.JLabel();
        Color31 = new javax.swing.JLabel();
        Color32 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Color1.setBackground(new java.awt.Color(255, 51, 51));
        Color1.setOpaque(true);
        Color1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color1MousePressed(evt);
            }
        });

        Color2.setBackground(new java.awt.Color(51, 51, 255));
        Color2.setOpaque(true);
        Color2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color2MousePressed(evt);
            }
        });

        Color3.setBackground(new java.awt.Color(0, 0, 0));
        Color3.setOpaque(true);
        Color3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color3MousePressed(evt);
            }
        });

        Color4.setBackground(new java.awt.Color(255, 255, 0));
        Color4.setOpaque(true);
        Color4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color4MousePressed(evt);
            }
        });

        Color5.setBackground(new java.awt.Color(255, 255, 255));
        Color5.setOpaque(true);
        Color5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color5MousePressed(evt);
            }
        });

        Color6.setBackground(new java.awt.Color(51, 204, 0));
        Color6.setOpaque(true);
        Color6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color6MousePressed(evt);
            }
        });

        Color7.setBackground(new java.awt.Color(255, 0, 204));
        Color7.setOpaque(true);
        Color7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color7MousePressed(evt);
            }
        });

        Color8.setBackground(new java.awt.Color(255, 153, 51));
        Color8.setOpaque(true);
        Color8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color8MousePressed(evt);
            }
        });

        Color9.setBackground(new java.awt.Color(153, 153, 153));
        Color9.setOpaque(true);
        Color9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color9MousePressed(evt);
            }
        });

        Color10.setBackground(new java.awt.Color(0, 255, 255));
        Color10.setOpaque(true);
        Color10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color10MousePressed(evt);
            }
        });

        Color11.setBackground(new java.awt.Color(0, 51, 153));
        Color11.setOpaque(true);
        Color11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color11MousePressed(evt);
            }
        });

        Color12.setBackground(new java.awt.Color(0, 153, 204));
        Color12.setOpaque(true);
        Color12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color12MousePressed(evt);
            }
        });

        Color13.setBackground(new java.awt.Color(153, 0, 102));
        Color13.setOpaque(true);
        Color13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color13MousePressed(evt);
            }
        });

        Color14.setBackground(new java.awt.Color(102, 0, 153));
        Color14.setOpaque(true);
        Color14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color14MousePressed(evt);
            }
        });

        Color15.setBackground(new java.awt.Color(153, 153, 0));
        Color15.setOpaque(true);
        Color15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color15MousePressed(evt);
            }
        });

        Color16.setBackground(new java.awt.Color(153, 0, 0));
        Color16.setOpaque(true);
        Color16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color16MousePressed(evt);
            }
        });

        Color17.setBackground(new java.awt.Color(0, 153, 102));
        Color17.setOpaque(true);
        Color17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color17MousePressed(evt);
            }
        });

        Color18.setBackground(new java.awt.Color(0, 51, 0));
        Color18.setOpaque(true);
        Color18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color18MousePressed(evt);
            }
        });

        Color19.setBackground(new java.awt.Color(204, 102, 255));
        Color19.setOpaque(true);
        Color19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color19MousePressed(evt);
            }
        });

        Color20.setBackground(new java.awt.Color(153, 102, 255));
        Color20.setOpaque(true);
        Color20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color20MousePressed(evt);
            }
        });

        Color21.setBackground(new java.awt.Color(0, 204, 51));
        Color21.setOpaque(true);
        Color21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color21MousePressed(evt);
            }
        });

        Color22.setBackground(new java.awt.Color(51, 0, 0));
        Color22.setOpaque(true);
        Color22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color22MousePressed(evt);
            }
        });

        Color23.setBackground(new java.awt.Color(102, 255, 204));
        Color23.setOpaque(true);
        Color23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color23MousePressed(evt);
            }
        });

        Color24.setBackground(new java.awt.Color(255, 102, 102));
        Color24.setOpaque(true);
        Color24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color24MousePressed(evt);
            }
        });

        Color25.setBackground(new java.awt.Color(51, 102, 255));
        Color25.setOpaque(true);
        Color25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color25MousePressed(evt);
            }
        });

        Color26.setBackground(new java.awt.Color(51, 51, 51));
        Color26.setOpaque(true);
        Color26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color26MousePressed(evt);
            }
        });

        Color27.setBackground(new java.awt.Color(255, 153, 153));
        Color27.setOpaque(true);
        Color27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color27MousePressed(evt);
            }
        });

        Color28.setBackground(new java.awt.Color(204, 204, 0));
        Color28.setOpaque(true);
        Color28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color28MousePressed(evt);
            }
        });

        Color29.setBackground(new java.awt.Color(0, 204, 153));
        Color29.setOpaque(true);
        Color29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color29MousePressed(evt);
            }
        });

        Color30.setBackground(new java.awt.Color(153, 255, 0));
        Color30.setOpaque(true);
        Color30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color30MousePressed(evt);
            }
        });

        Color31.setBackground(new java.awt.Color(102, 102, 0));
        Color31.setOpaque(true);
        Color31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color31MousePressed(evt);
            }
        });

        Color32.setBackground(new java.awt.Color(255, 51, 51));
        Color32.setOpaque(true);
        Color32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color32MousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("jLabel3");
        jLabel3.setOpaque(true);

        jLabel1.setText("Color Seleccionado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Color18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color20, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color22, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color21, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color24, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color23, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color25, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color28, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color27, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color30, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color29, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color32, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color31, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Color1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Color15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Color23, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color24, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color21, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color22, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color20, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color31, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color32, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color29, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color30, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color27, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color28, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color25, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Color1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color1MousePressed
        // Rojo
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);


    }//GEN-LAST:event_Color1MousePressed

    private void Color2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color2MousePressed
        // Azul
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);


    }//GEN-LAST:event_Color2MousePressed

    private void Color3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color3MousePressed
        // Negro
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color3MousePressed

    private void Color4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color4MousePressed
        // Amarillo
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color4MousePressed

    private void Color5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color5MousePressed
        // Blanco
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);


    }//GEN-LAST:event_Color5MousePressed

    private void Color6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color6MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color6MousePressed

    private void Color7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color7MousePressed
        // Rosa
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color7MousePressed

    private void Color8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color8MousePressed
        // Naranja
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color8MousePressed

    private void Color9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color9MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color9MousePressed

    private void Color10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color10MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color10MousePressed

    private void Color11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color11MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color11MousePressed

    private void Color12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color12MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color12MousePressed

    private void Color13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color13MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color13MousePressed

    private void Color14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color14MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color14MousePressed

    private void Color15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color15MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color15MousePressed

    private void Color16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color16MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color16MousePressed

    private void Color17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color17MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color17MousePressed

    private void Color18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color18MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color18MousePressed

    private void Color19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color19MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color19MousePressed

    private void Color20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color20MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color20MousePressed

    private void Color21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color21MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color21MousePressed

    private void Color22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color22MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color22MousePressed

    private void Color23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color23MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color23MousePressed

    private void Color24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color24MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color24MousePressed

    private void Color25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color25MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color25MousePressed

    private void Color26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color26MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color26MousePressed

    private void Color27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color27MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color27MousePressed

    private void Color28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color28MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color28MousePressed

    private void Color29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color29MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color29MousePressed

    private void Color30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color30MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color30MousePressed

    private void Color31MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color31MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color31MousePressed

    private void Color32MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color32MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        jLabel3.setBackground(colorSeleccionado);

    }//GEN-LAST:event_Color32MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Color1;
    private javax.swing.JLabel Color10;
    private javax.swing.JLabel Color11;
    private javax.swing.JLabel Color12;
    private javax.swing.JLabel Color13;
    private javax.swing.JLabel Color14;
    private javax.swing.JLabel Color15;
    private javax.swing.JLabel Color16;
    private javax.swing.JLabel Color17;
    private javax.swing.JLabel Color18;
    private javax.swing.JLabel Color19;
    private javax.swing.JLabel Color2;
    private javax.swing.JLabel Color20;
    private javax.swing.JLabel Color21;
    private javax.swing.JLabel Color22;
    private javax.swing.JLabel Color23;
    private javax.swing.JLabel Color24;
    private javax.swing.JLabel Color25;
    private javax.swing.JLabel Color26;
    private javax.swing.JLabel Color27;
    private javax.swing.JLabel Color28;
    private javax.swing.JLabel Color29;
    private javax.swing.JLabel Color3;
    private javax.swing.JLabel Color30;
    private javax.swing.JLabel Color31;
    private javax.swing.JLabel Color32;
    private javax.swing.JLabel Color4;
    private javax.swing.JLabel Color5;
    private javax.swing.JLabel Color6;
    private javax.swing.JLabel Color7;
    private javax.swing.JLabel Color8;
    private javax.swing.JLabel Color9;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
